orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
version: 2.1

jobs:
  my-custom-baa-job:
    machine: true
    resource_class: AwesomeCICD/ecr_t3_medium
    steps:
      - run: echo "HELLO BAA"  

workflows:
  ecr_workflow:
    jobs:
      - my-custom-baa-job:
          context: Context

